---
- project:
    check:
      jobs:
        - sf-rpm-build
        - tox-docs:
            nodeset: python-latest-pod
            vars:
              sphinx_build_dir: build
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py311:
            nodeset: python-latest-pod
    gate:
      jobs:
        - wait-for-changes-ahead:
            dependencies:
              - sf-rpm-build
              - tox-docs
              - tox-linters
              - tox-py311
        - sf-rpm-publish:
            dependencies:
              - wait-for-changes-ahead
        - sf-rpm-build
        - tox-docs:
            nodeset: python-latest-pod
            vars:
              sphinx_build_dir: build
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py311:
            nodeset: python-latest-pod
    release:
      jobs:
        - sf-rpm-publish
        - upload-pypi
