---
- project:
    check:
      jobs:
        - tox-docs:
            nodeset: python-latest-pod
            vars:
              sphinx_build_dir: build
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py311:
            nodeset: python-latest-pod
    gate:
      jobs:
        - wait-for-changes-ahead:
            dependencies:
              - tox-docs
              - tox-linters
              - tox-py311
        - tox-docs:
            nodeset: python-latest-pod
            vars:
              sphinx_build_dir: build
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py311:
            nodeset: python-latest-pod
    release:
      jobs:
        - upload-pypi
