---
- job:
    name: tox-py3
    parent: tox
    vars:
      tox_envlist: "py3"

- project:
    check:
      jobs:
        - tox-docs:
            nodeset: python-latest-pod
            vars:
              sphinx_build_dir: build
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py3:
            nodeset: python-latest-pod
    gate:
      jobs:
        - wait-for-changes-ahead:
            dependencies:
              - tox-docs
              - tox-linters
              - tox-py3
        - tox-docs:
            nodeset: python-latest-pod
            vars:
              sphinx_build_dir: build
        - tox-linters:
            nodeset: python-latest-pod
        - tox-py3:
            nodeset: python-latest-pod
    release:
      jobs:
        - upload-pypi
